### ISSUE TITLE
What search engine(s) do you favour? I'm assuming you're not a Google fan!

### ISSUE THREAD

**Issue by bram2000** [darrenmothersele/ama#1]

**Comment by darrenmothersele** [comment]
Good question.

The search engine is the filter through which we access the vast information available on the web. This is a powerful position to be in, considering the influence that the web has on our lives.

I would love to pay for a premium search service that operates on my behalf. But, unfortunately, that is not an option.

Instead we have chosen dependency on free services run by huge corporations that make billions of dollars by manipulating what we see online.

We license them free access to our valuable data. They build a rich profile of us from data about every aspect of our lives. They own our phone, email, documents, search history, DNS lookups, and web browsing.

I would suggest not using the same company for search as you use for email or other personal information.

Unfortunately, no search engine has the power of Google to produce such good results.

I use DuckDuckGo as my default search engine. I like to use an alternative as my first attempt to find what I'm looking for. I then revert to Google as a second resort.

80% of the time the results don't match what I'm expecting to see. In which case I prepend '!g ' to the search term in DuckDuckGo. This redirects to Google search results.

Somehow this also avoids the privacy pop-up I see when I go straight to Google:

Searching Google via the [DuckDuckGo Bang](https://duckduckgo.com/bang) leads me straight to the results. I don't know what happens to the annoying pop-up.

![googlesearch](https://cloud.githubusercontent.com/assets/230337/13319895/dcf6792e-dbbc-11e5-9994-be005b524ef3.png)

**Comment by bram2000** [comment]
Thanks for the detailed response. I thought you might say DuckDuckGo - I use that one myself (but not all of the time).

I wonder if the !g is somehow making the search anonymous with google?

**Comment by darrenmothersele** [comment]
https://twitter.com/inventur_es/status/703177387677085697

**Comment by bram2000** [comment]
Am I reading that right? You pay Google 5$/1000 searches to get the
_real_ results
rather than their personalised ones?
